en:
  docs:
    additional:
      heading: 'Additional Resources'
      order: 200
      items:
        end_user_guide:
          text: 'End User Guide'
          link: '/docs/user/'
          pdf: '/docs/suse-openstack-cloud-user_en.pdf'
          order: 100
        admin_user_guide:
          text: 'Admin Guide'
          link: '/docs/admin/'
          pdf: '/docs/suse-openstack-cloud-admin_en.pdf'
          order: 200
        supplement_guide:
          text: 'Supplement to Admin Guide and End User Guide'
          link: '/docs/supplement/'
          pdf: '/docs/suse-openstack-cloud-supplement_en.pdf'
          order: 300
